### ISSUE TITLE
Chrome not opening correctly if not from shortcut

### ISSUE THREAD

**Issue by DaveH1** [Bush2021/chrome_plus#84] opened 2024-06-09 15:01 UTC
Hi, I'm loving this 'extension' to Chrome, but I have one issue with it.
I'm using it with Google Chrome 125 64-bit on Windows 10.

If I run Chrome using its shortcut, everything work fine.
However, if Chrome runs from a link in an e-mail, say, it seems to not open correctly, and specifically, your DLL is not loaded.
Is that expected behaviour?
I am assuming that if Chrome is run from a link, the command line is as specified in the registry at -
HKEY_CLASSES_ROOT\ChromeHTML\shell\open\command

In my case, this is set to -
"C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\Program Files\Google\Chrome\User Data" --high-dpi-support=1 --force-device-scale-factor=1 --single-argument %1

I have the settings in chrome++.ini set to put the data folder at "C:\Program Files\Google\Chrome\User Data", which is where I want it, but this does not work when Chrome is run from a link, which is why it's included in the path above.

Every time I go between the methods of running Chrome, shortcut or link, it opens with the Sync switched off too, so everything has to be reinstalled.
This is driving me nuts!
Any ideas what's happening here?
Thanks, Dave.

**Comment by Bush2021** [comment] 2024-06-09 15:35
> However, if Chrome runs from a link in an e-mail, say, it seems to not open correctly, and specifically, your DLL is not loaded.
> Is that expected behaviour?

No. Chrome++ works fine on my machine.

Please provide the complete chrome++.ini information.

**Comment by DaveH1** [comment] 2024-06-09 16:59
OK, thanks for the quick response!
Here is my ini file.

[chrome++.zip](https://github.com/user-attachments/files/15753367/chrome%2B%2B.zip)

One thing I should perhaps mention which I did notice when I was configuring it was that the line -

CommandLine=--user-data-dir=C:\Progra~1\Google\Chrome\UserData

did not work if the normal path format was used, even when enclosed in quotations.
I found it only worked if I used 8.3 'DOS' names, as above.
I don't know if that is significant.
Cheers, Dave.

**Comment by Bush2021** [comment] 2024-06-10 03:53
@DaveH1 You may not specify user-data-dir in CommandLine, as I have included it in the source code. Instead, only use DataDir in [General] to avoid conflicts.

**Comment by DaveH1** [comment] 2024-06-10 14:02
Understood, I've now removed that entry from the INI file.
It hasn't made any difference to the issue though.
If I run Google Chrome from its shortcut, and look at the 'about' setting, I see this, which is presumably correct.

![Screenshot 57](https://github.com/Bush2021/chrome_plus/assets/6755753/813b6d8b-a066-4ec2-8d23-bd209656b717)

If I click on a link in an e-mail in the Outlook app, Chrome opens but when I look in the same place I see this, so Chrome Plus is not loading.

![Screenshot 58](https://github.com/Bush2021/chrome_plus/assets/6755753/efb17f90-c5db-4b1a-a3c7-ec7b3dd398c3)

Any idea why this would be?
Cheers, Dave.

**Comment by Bush2021** [comment] 2024-06-10 14:43
You may go to chrome://version/ and share the screenshots.

**Comment by DaveH1** [comment] 2024-06-10 16:48
OK, here's chrome://version/ when Chrome is run from its shortcut.

![Screenshot 1](https://github.com/Bush2021/chrome_plus/assets/6755753/432e7803-555d-483c-b12c-c9f94432ba2e)

And this is chrome://version/ when Chrome is run from an e-mail link in the Outlook app.
As you can see it's targetting a page on the MSFN forum.

![Screenshot 2](https://github.com/Bush2021/chrome_plus/assets/6755753/3edecb8d-1769-4ac1-83ad-4813d9390a27)

I hope this helps!
Cheers, Dave.

**Comment by Bush2021** [comment] 2024-06-11 05:08
I tested the installation from the official Google source in a virtual machine - adding version.dll and chrome++.ini (you can check if the location where you placed the DLL matches mine) - setting it as the default browser - launching from an external link. As shown in the image below, everything works fine.

![2024-06-11_124854](https://github.com/Bush2021/chrome_plus/assets/79072750/faeae402-003f-4cca-91cd-b2235ed3597e)
![2024-06-11_124656](https://github.com/Bush2021/chrome_plus/assets/79072750/8b955d45-9349-46a2-98d9-45df392ac80a)

Hence I believe the issue lies with your local environment. Unfortunately, you might need to troubleshoot why the DLL is not loading correctly.

Attached is the default registry content for Chrome installed in my virtual machine:
`"C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument %1`

Additionally, if you need to create a portable version, I may not recommend using the online installer from Google. A better approach is to use the offline installation package from https://github.com/Bush2021/chrome_installer. You can extract it twice using 7-Zip to obtain three items from Chrome-bin and then place them in the App folder from https://github.com/Bush2021/chrome_plus/releases. You can place it on the D drive, etc., to avoid conflicts with official version data files, as well as preventing the DLL from becoming invalid due to automatic updates.

**Comment by DaveH1** [comment] 2024-06-11 13:52
Thank you so much for doing these tests.
It does look like there is something on my system which is causing this, it's obviously not the normal expected behaviour!
There are other anomalies too. When Chrome is run from an e-mail link it not only doesn't load your DLL, it also opens with the sync disabled, which means that a lot of extensions do not load.
I modified the command line at HKEY_CLASSES_ROOT\ChromeHTML\shell\open\command as otherwise it generates a new clean user data folder in the default location, as it's your DLL which is telling it where the data folder should be.
Very odd.
I think what I will do as a test is set it up using the default user data folder location, remove all the stuff about scaling, and see what happens with an apparently standard installation.
If the problem is still there then, I don't know what to do!
Am I right in assuming that when a link is clicked in an e-mail on Windows 10, the default browser is simply run using the command in HKEY_CLASSES_ROOT\ChromeHTML\shell\open\command (if Chrome is the default browser)?
There's no other command paths involved anywhere?
Thanks again.
Cheers,
Dave.

**Comment by Bush2021** [comment] 2024-06-11 15:24
> There are other anomalies too. When Chrome is run from an e-mail link it not only doesn't load your DLL, it also opens with the sync disabled, which means that a lot of extensions do not load.
> I modified the command line at HKEY_CLASSES_ROOT\ChromeHTML\shell\open\command as otherwise it generates a new clean user data folder in the default location, as it's your DLL which is telling it where the data folder should be.

The issue with your computer is that, in some instances, the DLL is not loading correctly. When this happens, Chrome defaults to its standard settings, so "it generates a new clean user data folder in the default location" is the expected behavior. Since the original User Data and the portable version's User Data are not compatible, mixing their data when the DLL fails to load properly can cause corruption. This is also why Chrome repeatedly toggles synchronization. Therefore, it is best not to modify anything other than chrome++.ini, including the registry.

> I think what I will do as a test is set it up using the default user data folder location, remove all the stuff about scaling, and see what happens with an apparently standard installation.

Yes you may try this approach, but it is recommended to use a virtual machine to eliminate environmental interference. Alternatively, use my method below: download this 7z package (https://wormhole.app/O2O4P#tkpO-cLsuaAG8PeYfcTeuA) - extract it to a directory with appropriate permissions - copy all contents from your original User Data to the Data folder - set it as the default browser and try again.

> Am I right in assuming that when a link is clicked in an e-mail on Windows 10, the default browser is simply run using the command in HKEY_CLASSES_ROOT\ChromeHTML\shell\open\command (if Chrome is the default browser)?
> There's no other command paths involved anywhere?

Generally speaking, yes. And I don't think the issue with your computer is related to the command line; it should not affect DLL loading.

**Comment by DaveH1** [comment] 2024-06-11 17:34
OK, thanks again.
I tried restoring everything to standard using my existing installation of Google Chrome, and the result was the same.
I even tried copying the Command Line stated in Chrome://version when it was working correctly into HKEY_CLASSES_ROOT\ChromeHTML\shell\open\command.
Then when I ran Chrome from its shortcut, and when I ran it from an e-mail link, what was in the Command Line in Chrome://version was absolutely identical.
Still the former loaded version.dll but the latter did not load version.dll.
I cannot think of a single reason why this would be when Chrome is apparently being run with exactly the same parameters!
I have downloaed the version in your previous messgae, and i will now try with that to see if it does the same thing.
As you say, it could be something to do witht he fact that i'm using the standard Google dowload of Google Chrome.
Cheers, Dave.

**Comment by DaveH1** [comment] 2024-06-11 19:26
OK, I've downloaded the version you linked to, completely cleaned the system of the original installation of Google Chrome.
I now have what I assume is a completely portable version, which works fine when run from its shortcut.
The only problem is that you say to set it as my default browser.
How do I do that? If I use the option in the program, it just opens the Windows default apps settings, but of course Chrome is now no longer in the list of possible default browsers, as it now has no registry entries!

**Comment by Bush2021** [comment] 2024-06-12 03:19
@DaveH1 After clicking the corresponding option in Chrome, it will redirect to Windows Settings. There should be an entry for the newly added portable version of Chrome. Simply set it as the default.

**Comment by DaveH1** [comment] 2024-06-12 10:39
It's not there I'm afraid.
I'm not sure how it would be, as surely the portable version doesn't write the necessary registry entries?
Cheers, Dave.

**Comment by Bush2021** [comment] 2024-06-12 12:32
> It's not there I'm afraid. I'm not sure how it would be, as surely the portable version doesn't write the necessary registry entries? Cheers, Dave.

Okay...You may try https://github.com/sil3nc3/PortableRegistrator .

**Comment by DaveH1** [comment] 2024-06-12 16:39
Thanks, what a great utility!
It seems to have worked, but the problem is still there.
When I run Chrome with its shortcut, all is fine.
When I click on a link in an e-mail, Chrome opens the wrong size and position, and asks me to sign in.
Your DLL does not load, and it consequentially generates a new clean User Data folder in the default location.
Again, I have absolutely no idea why it's doing this, and why it doesn't do it on your system.
I'm now completely at a loss, and searches don't seem to find anything relevant.
Any more suggestions gratefully received!

**Comment by Bush2021** [comment] 2024-06-12 17:37
@DaveH1 Try https://github.com/Bush2021/chrome_plus/tree/main/setdll and follow the steps in the instructions. Of course, you may first delete the current version.dll. If there are still issues, then I'm afraid I can't help further.

**Comment by DaveH1** [comment] 2024-06-12 17:43
Thanks, I will give that a try and report back.

**Comment by DaveH1** [comment] 2024-06-12 23:05
Thank you, that has fixed it!
I don't know what was wrong before, perhaps I didn't do something that I should have done when I first started using Chrome Plus. All I did was just copy the DLL to the folder when chrome.exe was, with the INI file, and that seemed to work, at least when Chrome was run from a shortcut.
Anyway, it all seems to be working fine now, even from the links in e-mails.
I hope this helps anyone else who has the same issue.

Just an off-topic aside, would you recommend sticking with the portable version of Chrome that you linked to, rather than installing the full version from Google again?
What happens with updates? There seems to be no update check now when Chrome runs.
Cheers, and thanks for all the help here.
Dave.

**Comment by Bush2021** [comment] 2024-06-13 01:54
Generally speaking, I recommend that all users use the offline installer without the automatic update component to create a portable version, as chrome++ might become invalid due to changes in Chrome’s interface. It is advisable to back up and test before manually updating. You may also check out this tool: https://github.com/libsgh/chrome_updater.

For users like you who have to use setdll for various reasons, you need to rerun inject.bat each time you update Chrome to ensure the DLL loads correctly. Updating chrome++ does not require resetting setdll.

That’s all. Closing this issue as resolved.

**Closed by Bush2021** 2024-06-13 01:54 UTC

**Comment by DaveH1** [comment] 2024-06-13 11:11
Thank you so much.
I will stick with the portable version.
Apart from anything else, it gets rid of the bloat of the Google Update services!
Can I ask just one more thing, again off-topic.
You say that your DLLs will not work on Windows XP. I use Thorium Legacy on the XP side of my multi-boot machine, and I'd love to be able to use Chrome Plus with that.
Is that just because of the way they're compiled, or are there more fundamental reasons?
If it's the former, could an XP compatible version be compiled?
Cheers, Dave.
